### PR TITLE
Use @v1 instead of @master in examples

### PR DESCRIPTION
**Pull request by oleg-derevenetz**
Use of the `@master` tag is a bit unusual for an Action.

### CODE REVIEW

**Comment by platisd** [comment]
I don't know, is it so unusual? :grin:

**Comment by platisd** [comment]
Also just noticed that our tags are a bit inconsistent :sweat_smile: 

image

**Comment by oleg-derevenetz** [comment]
> I don't know, is it so unusual? 😁

Well, new major versions might break the behavior or API, so yes, using `@master`/`@latest` is a bit unusual (unless you are 100% sure what are you doing, e.g. if you are a developer of this Action) :)

**Comment by platisd** [comment]
Yeah I know it's more _reliable_ sticking to a version, but having it as `@master` in the documentation and letting users decide whether to stick to a version or not, has some benefits:
1. We don't have to update `README` for new releases
2. As maintainers we are a bit more inclined to keep `master` :green_circle:
3. If a regression is introduced it's more likely it will be discovered quicker, as the chances are higher there are users with the latest and greatest stuff who will report the issue

What do you think?

**Comment by oleg-derevenetz** [comment]
> We don't have to update README for new releases

If we use the major version tag, we will need to update it only when the major version is changed (`@v1` -> `@v2`), and this normally would happen only when some breaking changes are implemented (for example, some input parameter has been removed). I believe this will happen relatively rarely.

> As maintainers we are a bit more inclined to keep `master`

Yes, because we are maintainers and we know what we are doing :)

> If a regression is introduced it's more likely it will be discovered quicker, as the chances are higher there are users with the latest and greatest stuff who will report the issue

If people will use `@v1` tag and no breaking changes are introduced, they will get the latest "non-breaking" version anyway, because this tag should always point to the latest `1.X.Y` (or `v1.X.Y`) version tag. And if there are breaking changes, then users will not suffer from them, because breaking changes should go to the new major tag (e.g. `@v2`).

**Comment by platisd** [comment]
Let's follow the conventions then and go with the `v` prefix for releases from now on.

**Pull request merged**
