### PR TITLE
Remove the extra backslash

### PR DESCRIPTION
**Pull request by oleg-derevenetz**

### CODE REVIEW

**Comment by renefritze** [comment]
How about adding https://github.com/koalaman/shellcheck-precommit to the config to catch this type of thing automatically in the future?

**Comment by oleg-derevenetz** [comment]
> How about adding https://github.com/koalaman/shellcheck-precommit to the config to catch this type of thing automatically in the future?

I don't use the `pre-commit` tool. If you use it, you are welcome to do this.

**Comment by oleg-derevenetz** [comment]
BTW `shellcheck` is not able to catch this extra backslash yet (if the last line of the script ends with a line break). But let it be.

**Review by platisd — APPROVED** [review]

**Comment by platisd** [comment]
> How about adding https://github.com/koalaman/shellcheck-precommit to the config to catch this type of thing automatically in the future?

Not a big fan of them myself either, prefer a CI check instead. :P

**Comment by renefritze** [comment]
> > How about adding https://github.com/koalaman/shellcheck-precommit to the config to catch this type of thing automatically in the future?
> 
> Not a big fan of them myself either, prefer a CI check instead. :P

IMO it's best to combine both. One of my workflows always does `pre-commit run -a` to ensure the PR is actually following formatting, etc encoded through tools in the pre-commit setup.

**Comment by platisd** [comment]
Btw, I am also open to introducing this as a pre-commit too. :}

**Pull request merged**
