### PR TITLE
Add jq to requirements.txt

### PR DESCRIPTION
**Pull request by nsmithtt**

### CODE REVIEW

**Comment by platisd** [comment]
Hi, can you please elaborate why this is needed?
I can't see where we use `jq` in the Python script.

**Comment by nsmithtt** [comment]
`jq` seems to be used in `action_launcher.bash` [here](https://github.com/platisd/clang-tidy-pr-comments/blob/88780c4ca5471b97de8f228219d1e39b1a472142/action_launcher.bash#L6).

I'm using this action on a private runner that doesn't have `jq` installed by default, I run into this issue:
```
Run "${GITHUB_ACTION_PATH}/action_launcher.bash"
/__w/_actions/platisd/clang-tidy-pr-comments/v1.6.0/action_launcher.bash: line 6: jq: command not found
```

**Comment by nsmithtt** [comment]
I just realized that this won't fix the issue I'm running into because the pip package doesn't install the cli interface.  I mistakenly thought it did

**Comment by nsmithtt** [comment]
Closing this PR, filed issue here: https://github.com/platisd/clang-tidy-pr-comments/issues/88

**Pull request closed without merging**
