### PR TITLE
Add new `python_path` option to use existing Python installation

### LINKED ISSUE #84: Add option to use existing Python installation
Due to [this unresolved issue](https://github.com/actions/setup-python/issues/871) with the `setup-python` action I'm currently unable to use this action on our self-hosted runners. Since we already have Python 3.12 pre-installed on the runners however, it would be great if there was an option to skip the installation step and simply use the existing installation instead!

Edit: Or maybe even better a `python-path` option, that if set, skips the `setup-python` action and uses it to create the `venv` (i.e. something like `"${{ steps.setup-python.outputs.python-path || inputs.python_path }}" -m venv "${GITHUB_ACTION_PATH}/venv"`)

### PR DESCRIPTION
**Pull request by psalz**
Resolves #84.

Not sure if the additional CI job for testing the option is needed, given that the other options aren't being tested either. FWIW, I tested the change in our workflow and everything works as intended!

### CODE REVIEW

**Review by platisd — APPROVED** [review]
Looks good :+1:

**Comment by psalz** [comment]
Thanks! Will you cut a new release soon or should I use my fork for the time being?

**Comment by platisd** [comment]
Right, thanks for reminding me :+1:

**Comment by platisd** [comment]
Done! It's `v1.6.0`

**Comment by psalz** [comment]
Awesome, thanks!

**Pull request merged**
